### ISSUE TITLE
Licence

### ISSUE THREAD

**Issue by fretchen** [openkfw/open-geodata-model#1]
What is the appropiate Licence ? 

- It looks to me very much like the other contents of the RMMV context and then it would be similiar to the one of the [d4dtools](https://github.com/openkfw/d4dtools) CC-BY-NC-SA-4.0

**Comment by Jo-Schie** [comment]
thanks for the reminder @fretchen . i am not really sure, if we can use a non-commercial Liscence for this content, given that third parties who collect the data are doing this as a commercial service for the data users... 

I think a better fit is "Attribution-ShareAlike 4.0" see [here](https://creativecommons.org/licenses/by-sa/4.0/) . I will add this as for now but it would be good if we could get some Feedback on the question whether the liscence should be non-commercial.

**Comment by fretchen** [comment]
Sounds good. I will take a loop with our internal lawyers.

**Comment by fretchen** [comment]
@maja4dev any opinions in this regard ?

**Comment by fretchen** [comment]
Closed with #7
