### ISSUE TITLE
Text missing/Links not working in RMMV Guidebook Factsheet Annex 3.1

### ISSUE THREAD

**Issue by JulesT94** [openkfw/open-geodata-model#4]
In RMMV Guidebook p. 145 there seems to be text missing when turning to the next page 146.
The sentence on p. 146 starts out of nowhere.. some text before might have gotten lost.

Once it is added, it should also be added in the github website text. 
@Maja4dev
@Jo-Schie

**Comment by JulesT94** [comment]
In addition, there is text existing on p. 145 that is displayed in white. Hence, you cannot read it. 
However, if you search for the text via ctrl+F - white space will be marked (in green) as if there was hidden text. 
![white text](https://user-images.githubusercontent.com/127729470/224975247-cca055e1-a3a7-4aae-8490-2988659c5e23.PNG)

**Comment by JulesT94** [comment]
Another bug i found is that on p. 146 of the RMMV handbook, the link to OpenGIS is not working. The link is entered at the end of the page after making a reference to the WG S84 datum which is used by OpenStreetMaps and GoogleMaps. My questions would be - why do we reference to OpenGIS and if we want to insert the link into the documentation - what do we do? @Jo-Schie @Maja4Dev :)

**Comment by JulesT94** [comment]
Another small comment (i don't know if that's relevant for you) in the RMMV Handbook you define KML in footnotes twice. Once only in brief at the end of p. 145 and once again a little more in detail at the end of p. 146.

**Comment by JulesT94** [comment]
I used [this link](https://www.kfw-entwicklungsbank.de/PDF/Download-Center/Themenpublikationen/RMMV-Factsheets/Annex3.1.pdf) Fred sent me for annex 3 of the RMMV Handbook. 
But it seems there are two different versions of the annex. In the one you mentioned the bugs do indeed not exist, while they exist in the link Fred sent me for the Annex.

**Comment by Maja4Dev** [comment]
The document you got from Fred is an automatically converted Word Version of the officiall PDF Version for your easier use in copying the text. Please always check with the PDF Version, no need to correct the Word version.--Diese Nachricht wurde von meinem Android Mobiltelefon mit WEB.DE Mail gesendet.Am 03.04.23, 14:34 schrieb JulesT94 ***@***.***>:

   
  I used this link Fred sent me for annex 3 of the RMMV Handbook. But it seems there are two different versions of the annex. In the one you mentioned the bugs do indeed not exist, while they exist in the link Fred sent me for the Annex.

**Comment by fretchen** [comment]
I think that this was fixed as the link on the website is now pointing to the documentation here.
