### ISSUE TITLE
Change Categories on the left side of the main page Project Location Model

### ISSUE THREAD

**Issue by Maja4Dev** [openkfw/open-geodata-model#41]
- Introduction
- Project Location Model Templates and sample ToR (EN/FR) 
- Technical Notes on the Project Location Model
- FAQ
- Project Location Icons
- Additional Information Material 
   incl. Tutorials (please move Egypt tutorial to the Github/d4d tools -> Data Sources

**Comment by Maja4Dev** [comment]
#41

**Comment by fretchen** [comment]
I suggest the following procedure:

- Wait for #20 to be merged. 
- Then split the content of the [index ](docs/index.md) file as suggested and create a new PR (or use it in #42 ).

The move of the tutorials can be done spearately.

- @Maja4Dev would you then create an [extra tutorial section](https://github.com/openkfw/d4dtools/tree/main/docs) in this and [move the file](https://github.com/openkfw/open-geodata-model/blob/main/docs/tutorials/open_data_on_broadband_in_egypt.ipynb) over there ? 
- What is meant with "move it towards Data Sources ?"

**Comment by Jo-Schie** [comment]
thanks fred

**Comment by Maja4Dev** [comment]
I cannot do this alone and I cannot wait until tomorrow. That's why I did already most of it with Surafel. Do I have to do everything again now?

**Comment by fretchen** [comment]
Once #20 is closed I can propose a fix there.

**Comment by fretchen** [comment]
In https://github.com/openkfw/open-geodata-model/pull/20/commits/640654d12d243c0866759b97b5e20332a6a94ec0 we have a lot of suggestions on how to break apart the main file. 

# Introduction 

This flows until the end of when to collect project location information


# Project Location Model Templates and sample ToR (EN/FR)

This is bit funky, but we will see what is meant with this. So I simply copy the current notes from the index.md file.

```

## Link to Project Location Data Collection Template 

**You can find the current version of the projection location data collection template [here](https://github.com/openkfw/open-geodata-model/blob/main/Project_Location_Data_Template_V02.xlsx).**

## Link to ToR
```

## Technical Notes on the Project Location Model

Until the end of table 2

## FAQs
The rest of it.

**Comment by Maja4Dev** [comment]
I dont understand what this means.
