### ISSUE TITLE
Release prep for v1

### ISSUE THREAD

**Issue by fretchen** [openkfw/open-geodata-model#46]
In this issue we collect important things that need to be done to finish [milestone v1](https://github.com/openkfw/open-geodata-model/milestone/2) and then transform them into issues where appropiate.

@Maja4Dev, @goergen95  and @Jo-Schie any lists ?

Questions I have are:

- French stuff is required or optional ?
- Readme updates are required or optional ?
- Any technical details required ?
- Workflows from #34 required ?
- Icons of #8 required for v1 ?
- Governance of changes #23 ?

What else ?

**Comment by fretchen** [comment]
Here is an old todo that was hidden in the `index.md` file. @Maja4Dev  what is meant with this ? 

- [ ] TODO: Sticky notes into Description in table ( -> @S-r-f-l )
- [ ] TODO 2: Check contents of readme and table and cross-check with existing documentation here. Choose whether to include it into the more "general part" or the "technical notes" (Think of audience) (-> @Maja4Dev )

**Comment by Jo-Schie** [comment]
I was wondering whether we could use our colors? https://brand-guide.kfw.de/ ... not sure how important you think this is but it may please internal people.

**Comment by Maja4Dev** [comment]
> In this issue we collect important things that need to be done to finish [milestone v1](https://github.com/openkfw/open-geodata-model/milestone/2) and then transform them into issues where appropiate.
> 
> @Maja4Dev, @goergen95 and @Jo-Schie any lists ?
> 
> Questions I have are:
> 
> * French stuff is required or optional ? The already exisiting french texts should be published in this release, yes
> * Readme updates are required or optional ? This was already completed. 
> * Any technical details required ? This was done as part of the updates already done. 
> * Workflows from [Describe the data collection and process #34](https://github.com/openkfw/open-geodata-model/issues/34) required ? I dont know what this is. Please leave it out, if not yet published. This should be a separate issue. 
> * Icons of [Add Icons from Annex 3.3 from the Guidebook ? #8](https://github.com/openkfw/open-geodata-model/issues/8) required for v1 ? No, because we dont have any new ones yet. 
> * Governance of changes [Governance of future changes to the specification looks like #23](https://github.com/openkfw/open-geodata-model/issues/23) ? Please make this a new issue!
> 
> What else ? Please release the updates now.
