### ISSUE TITLE
Commenting

### ISSUE THREAD

**Issue by fretchen** [openkfw/open-geodata-model#6]
Do we want something fancy for commenting like we use at d4dtools ? @Jo-Schie 

For an example see [here](https://openkfw.github.io/d4dtools/drones/#links-to-further-sources).

**Comment by Jo-Schie** [comment]
Hi @fretchen . Is it possible to avoid SPAM? If so, I would guess it is good to try it with comments. When it becomes overwhelming or badly managed then we can deactivate it again.

**Comment by fretchen** [comment]
To make it work someone with adminstrative rights has to enable the discussions forum. (@Jo-Schie or @jzakotnik)
And spam is suppressed by the fact that only logged in github users can comment...
