### ISSUE TITLE
Use external DAC codes 

### ISSUE THREAD

**Issue by fretchen** [openkfw/open-geodata-model#69]
### Discussed in https://github.com/openkfw/open-geodata-model/discussions/68

<div type='discussions-op-text'>

<sup>Originally posted by **fretchen** June 14, 2024</sup>
I saw in the Excel file that there is a DAC Purpose Codes worksheet. What is this based on ? Is it correct that the column on the *DAC 5 code* is based on the published iati standards [version 2.03](https://iatistandard.org/en/iati-standard/203/codelists/sector/) ? Same on the description. Is this the description from the published standard or has it been edited ?

I assume that @Maja4Dev  might know more about this ?</div>

Given that we use the external DAC codes we should also make use of them and reference them. My suggested approach would be:

- [ ] Copy the official version in identifiable fashion into this repo. This might be the csv or json, no strong opinions here.
- [ ] Provide automatic tests that verify that the DAC codes used in our templates are identical to the ones of the official versions.

## Potential benefits

- As the DAC codes are updated we have automatic tests that allow us to detect important changes. This would also allow us to make sur that different technical implementations of the project location template adhere to the same standard.
- In the long term we could try to create the worksheets in the excel files directly from the external DAC lists, making updates easier. However, this would have to be most likely left to later stages.

@Jo-Schie and @Maja4Dev if there is interest in this I could prepare a draft PR to make clearer what I have in mind.

**Comment by Maja4Dev** [comment]
I agree, this would be perfect!
